// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.IPBlacklistLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("ipAddress")]
        public string IpAddress { get; set; }

        [JsonProperty("isIPBlacklisted")]
        public bool? IsIpBlacklisted { get; set; }

        [JsonProperty("inbound")]
        public Inbound Inbound { get; set; }

        [JsonProperty("outbound")]
        public object Outbound { get; set; }

        [JsonProperty("threatLevel")]
        public string ThreatLevel { get; set; }

        [JsonProperty("ipDetails")]
        public IpDetails IpDetails { get; set; }
    }

    public partial class Inbound
    {
        [JsonProperty("found")]
        public bool? Found { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class IpDetails
    {
        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("coordinates")]
        public double?[] Coordinates { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("regionName")]
        public string RegionName { get; set; }

        [JsonProperty("postalCode")]
        public long? PostalCode { get; set; }

        [JsonProperty("continent")]
        public string Continent { get; set; }

        [JsonProperty("continentName")]
        public string ContinentName { get; set; }

        [JsonProperty("accuracyRadius")]
        public long? AccuracyRadius { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
